name: "Automated Code Analysis and Security Fix"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  analyze-and-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          python -m pip install --upgrade pip
          pip install requests flask
          echo "Dependencies installed."

      - name: Run Security Analysis Script
        run: |
          echo 'Creating security scan script...'
          echo '
import os
import re

def scan_for_vulnerabilities():
    with open("main.py", "r") as file:
        content = file.read()
        # SQL Injection detection
        sqli_pattern = r"(SELECT.*FROM.*WHERE.*\' OR 1=1--)"
        if re.search(sqli_pattern, content):
            print("Potential SQL Injection vulnerability detected!")
            fix_sql_injection()
        # XSS detection
        xss_pattern = r"(<script.*>.*</script>)"
        if re.search(xss_pattern, content):
            print("Potential XSS vulnerability detected!")
            fix_xss_vulnerability()

def fix_sql_injection():
    print("Fixing SQL Injection vulnerability...")
    with open("main.py", "r") as file:
        content = file.read()
    content = content.replace("\' OR 1=1--", "")
    with open("main.py", "w") as file:
        file.write(content)

def fix_xss_vulnerability():
    print("Fixing XSS vulnerability...")
    with open("main.py", "r") as file:
        content = file.read()
    content = content.replace("<script>", "&lt;script&gt;").replace("</script>", "&lt;/script&gt;")
    with open("main.py", "w") as file:
        file.write(content)

scan_for_vulnerabilities()
          ' > scripts/security_scan.py
          echo "Security scan script created."

      - name: Execute Security Scan Script
        run: |
          echo "Executing security scan script..."
          python ./scripts/security_scan.py
          echo "Security scan script executed."

      - name: Commit and Push Fixed Code
        run: |
          echo "Committing changes..."
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Fixed vulnerabilities and improved code security"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
